# Generated by Django 3.1.7 on 2021-08-22 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210822_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Title', 'verbose_name_plural': 'Titles'},
        ),
        migrations.AddField(
            model_name='title',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='pub_date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique-author-title'),
        ),
    ]
